interface Baggage {
  airlineCode: string;
  flightNumber: string;
  wayType: number;
  code: string;
  description: number;
  weight: number;
  currency: string;
  price: number;
  origin: string;
  destination: string;
  //   segID: null;
}
interface Meal {
  airlineCode: string;
  flightNumber: string;
  wayType: number;
  code: string;
  description: number;
  airlineDescription: string;
  quantity: number;
  currency: string;
  price: number;
  origin: string;
  destination: string;
  segID: null;
}
interface Seat {
  airlineCode: string;
  flightNumber: string;
  craftType: string;
  origin: string;
  destination: string;
  availablityType: number;
  description: string;
  code: string;
  rowNo: string;
  seatNo: string;
  seatType: number;
  seatWayType: number;
  compartment: number;
  deck: number;
  currency: number;
  price: number;
  //   craftDeviation: null;
  //   compartmentDesignator: null;
  //   segID: null;
}
interface Passenger {
  paxId: number;
  ssr: [];
  panrequired: boolean;
  passportRequired: boolean;
  title: string;
  firstName: string;
  lastName: string;
  passengerNumber: number;
  //   docTypeCode: null;
  //   docNumber: null;
  //   expirationDate: null;
  paxType: number;
  //   dateOfBirth: null;
  gender: number;
  //   passportNo: null;
  //   passportExpiry: null;
  //   addressLine1: 'Koshambi';
  //   addressLine2: null;
  //   totalCost: null;
  //   balanceDue: null;
  //   issuedDate: null;
  seatDynamic: Array<Seat>;
  mealDynamic: Array<Meal>;
  baggage: Array<Baggage>;
  //   fare: null;
  city: string;
  countryCode: string;
  //   countryName: null;
  nationality: string;
  contactNo: string;
  email: string;
  isLeadPax: boolean;
  //   fFAirlineCode: null;
  //   fFNumber: null;
  //   gSTCompanyAddress: null;
  //   gSTCompanyContactNumber: null;
  //   gSTCompanyName: null;
  //   gSTNumber: null;
  //   gSTCompanyEmail: null;
  //   ticket: null;
  //   SegmentAdditionalInfo: null;
  //   items: null;
  IsPANRequired: boolean;
  IsPassportRequired: boolean;
  //   PAN: null;
}
interface FlightDetails {
  origin: string;
  destination: string;
  //   artSupplierCredential: null;
  //   result: null;
  //   agency: null;
  //   fareType: null;
  //   tokenId: null;
  adultCount: number;
  childCount: number;
  infantCount: number;
  directFlight: boolean;
  specialFareType: string;
  nextDayFlag: boolean;
  journeyType: string;
  prefclass: string;
  resultCategory: string;
  //   oneWayResultIndex: null;
  //   roundTripResultIndex: null;
  //   traceId: null;
  //   preferredAirlines: null;
  segments: Array<{
    //   depTime: null;
    //   depDate: null;
    //   arrivalAirport: null;
    //   departureAirport: null;
    origin: string;
    //   IsReturn: null;
    destination: string;
    flightCabinClass: string;
    //   DepartureAirport: null;
    //   ArrivalAirport: null;
    //   DepDate: null;
    //   DepTime: null;
    preferredDepartureTime: string;
    //   preferredArrivalTime: null;
  }>;
  //   sources: null;
  onwarddate: string;
  returndate: string;
  //   leastPrice: null;
  //   highestPrice: null;
  gSTDetailsRequired: boolean;
  originCountryCode: string;
  //   flightNumber: null;
  destinationCountryCode: string;
  domIntFlag: string;
  isSeriesFareCalendar: string;
}
export interface PaymentRequest {
  agency: string;
  //   resultIndex: null;
  resultSessionId: string;
  passengers: Array<Passenger>;

  //   endUserIp: null;
  //   tokenId: null;
  //   traceId: null;
  contactNo: string;
  email: string;
  //   gSTCompanyAddress: null;
  //   gSTCompanyContactNumber: null;
  //   gSTCompanyName: null;
  //   gSTNumber: null;
  //   gSTCompanyEmail: null;
  fareMismatch: boolean;
  passangerCount: number;
  publishedFare: number;
  offeredFare: number;
  pf: number;
  lcc: true;
  dobAirAshiya: boolean;
  gSTDetailsRequired: string;
  //   supplierId: null;
  //   artSSRResponse: null;
  flightDetailsRequest: FlightDetails;
  //   sosSegment: null;
  //   adminremarks: '';
  pGUserMappingId: string;
  pGUserId: string;
  //   encRequest: null;
}
