export interface PaymentReponse {
  marchentSalt: string;
  marchentKey: string;
  //   accessCode: null;
  //   workingCode: null;
  //   tid: null;
  //   orderid: null;
  //   currency: null;
  //   language: null;
  //   id: null;
  creditInWallet: string;
  //   toDate: null;
  //   fromDate: null;
  //   marchentid: null;
  pgname: string;
  paymentGatewayModel: {
    // clientFlag: null;
    id: number;
    pgCode: string;
    description: string;
    pgUrl: string;
    successUrl: string;
    failureUrl: string;
    cancelUrl: string;
    transectionCharge: number;
    marchentSalt: string;
    marchentKey: string;
    // accessKey: null;
    // workingKey: null;
    // marchentid: null;
  };
  //   mihpayid: null;
  //   mode1: null;
  surl: string;
  curl: string;
  furl: string;
  //   status: null;
  //   key1: null;
  txnid: string;
  amount: string;
  productinfo: string;
  firstname: string;
  lastname: string;
  //   address1: null;
  //   city: null;
  //   state: null;
  //   country: null;
  //   zipcode: null;
  email: string;
  phone: string;
  hash: string;
  //   error: null;
  //   bankcode: null;
  //   pgtype: null;
  //   bank_ref_num: null;
  //   unmappedstatus: null;
  enforcePayMethod: string;
}
